### ISSUE TITLE
List command is not working

### ISSUE THREAD

**Issue by zentetsukenz** [taylor/kiex#63]
`kiex list` command throw out an error

```
kiex elixirs

   elixir-1.3.3/Users/wiwattamongkhonchit/.kiex/bin/kiex: line 946: elixir-1.3.3: syntax error: invalid arithmetic operator (error token is ".3.3")
```

I'm not bash script expert, so I'm not sure what's going on here but looking from the error and the code it seems like 

```
target_alias_list="${ealiases[$version]}"
```

array dereference is trying to evaluate `$version` expression which currently contain `elixir-1.x.x` and throw an error.

**Comment by aboroska** [comment]
The is caused by #61 that introduces associative arrays `declare -A ealiases=()` which is a Bash 4 feature. If you use Bash 3.2 (that comes with macOS Sierra for example) the problem manifests.

So `kiex` master is unusable on vanilla mac because Apple is reluctant to upgrade Bash due to the licensing change in Bash 4. The workaround is to upgrade Bash manually http://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx

Sidenote: Perl5 is the most portable scripting platform.

**Comment by taylor** [comment]
Reverted changes until this can be written to support Bash 3.2.

**Comment by greymouser** [comment]
@taylor gahhhhh, my bad. I already have the fix for Bash 3 here: https://github.com/greymouser/kiex/tree/unalias+delete

I'm not sure I know the correct git steps in this case; my branch doesn't have the rollback. Should I create a new branch from upstream master on my side, revert the reversion, and cherry-pick my change in? Advice appreciated.

**Comment by greymouser** [comment]
@taylor A new pull request against master has been created with Bash 3 support.
